---
  - name: Enable universe repository
    apt_repository:
      repo: "{{ item }}"
    loop:
      - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
      - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
      - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"

  - name: Install common tools
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - jq
      - tree
      - vim

  - name: Set VIM as default editor
    alternatives:
      name: editor
      path: /usr/bin/vim.basic
