---
  - name: "Creating directories"
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
      group: "{{ elvmasterd_user }}"
      owner: "{{ elvmasterd_group }}"
    with_items:
      - "{{ eluvio_base_dir }}"
      - "{{ eluvio_base_dir }}/var"
      - "{{ eluvio_base_dir }}/bin"
      - "{{ eluvio_base_dir }}/conf"
      - "{{ eluvio_base_dir }}/var/{{ blockchain_network }}"
      - "{{ fabric_data }}"

  - name: Set Eluvio permissions
    file:
      path: "{{ eluvio_base_dir }}"
      owner: "{{ elvmasterd_user }}"
      group: "{{ elvmasterd_group }}"
      recurse: yes

  - name: Generate systemd unit
    template:
      src: templates/elvmasterd.service.j2
      dest: /etc/systemd/system/elvmasterd.service

  - name: Generate elvmaster TOML
    template:
      src: templates/blockchain.toml.j2
      dest: "{{ eluvio_base_dir }}/conf/{{ blockchain_network }}.toml"

  - name: Generate secrets
    template:
      src: templates/secret.env.j2
      dest: "{{ eluvio_base_dir }}/conf/secret.env"
      mode: 0600
      owner: root
      group: root

  - name: stop elvmasterd
    systemd:
      state: stopped
      name: elvmasterd
      daemon_reload: yes
    failed_when: no

  - name: "Extract elvmasterd into {{ eluvio_base_dir }}/bin"
    unarchive:
      src: "{{ installer_location }}/{{ elvmasterd_tgz }}"
      dest: "{{ eluvio_base_dir }}"
      remote_src: yes

  - name: Set 'elvmasterd' to executeable
    file:
      path: "{{ eluvio_base_dir }}/bin/elvmasterd"
      mode: 0755
