---
  - name: Initialize elvmasterd blockchain
    become: yes
    become_user: "{{ elvmasterd_user }}"
    environment:
      HDWALLET_PASSPHRASE: "{{ wallet_secret }}"
      HDWALLET_MNEMONIC: "{{ mnemonic12 }}"
      NODE_NODE_ACCOUNT: "0"
      NODE_KMS_ACCOUNT: "1"
      NODE_KMS_PASSPHRASE: "{{ wallet_secret }}"
      NODE_NODE_PASSPHRASE: "{{ wallet_secret }}"
    shell: |
      {{ eluvio_base_dir }}/bin/elvmasterd init \
      --config {{ eluvio_base_dir }}/conf/{{ blockchain_network }}.toml \
      --log-file {{ eluvio_base_dir }}/var/{{ blockchain_network }}/elvmasterd.log
    args:
      creates: "{{ eluvio_base_dir }}/var/{{ blockchain_network }}/elvmasterd"

  # Will move this to dynamically created
  - name: Seed the peer list
    copy:
      src: "files/static-nodes_{{ blockchain_network }}.json"
      dest: "{{ eluvio_base_dir }}/var/{{ blockchain_network }}/elvmasterd/static-nodes.json"
      owner: "{{ elvmasterd_user }}"
      group: "{{ elvmasterd_group }}"
      mode: 0644
