---
  - name: "Start service qfab"
    systemd:
      name: qfab
      state: started
      enabled: yes
      daemon_reload: yes

  - name: Allow access to fabric port
    ufw:
      rule: allow
      proto: tcp
      port: '{{ item }}'
    with_items:
      - "{{ api_port }}"
