---
  - name: "Deny everything and enable UFW"
    ufw:
      state: enabled
      policy: deny
      direction: incoming

  - name: "Enable ssh access on firewall"
    ufw:
      rule: allow
      port: "{{ item }}"
    loop: "{{ ssh_ports }}"
