---
  - name: "Deny everything and enable UFW"
    ufw:
      state: enabled
      policy: deny
      direction: incoming

  - name: "Enable ssh (as defined in /etc/services) access on firewall"
    ufw:
      rule: allow
      port: ssh
