---
- name: Set networking net.core.rmem_max
  sysctl:
      name: net.core.rmem_max
      value: 262144000
      sysctl_set: yes
      state: present

- name: Setting net.core.rmem_default
  sysctl:
    name: net.core.rmem_default
    value: 262144000
    sysctl_set: yes
    state: present

- name: Setting net.core.netdev_max_backlog
  sysctl:
    name: net.core.netdev_max_backlog
    value: 10000
    sysctl_set: yes
    state: present

- name: Setting net.core.default_qdisc
  sysctl:
    name: net.core.default_qdisc
    value: fq
    sysctl_set: yes
    state: present

- name: Enabling BBR
  sysctl:
    name: net.ipv4.tcp_congestion_control
    value: bbr
    sysctl_set: yes
    state: present
    reload: yes

- name: Open up connection max on netfliter
  sysctl:
    name: net.netfilter.nf_conntrack_max
    value: "{{ open_netfilter }}"
    sysctl_set: yes
    state: present
    reload: yes
  when: open_netfilter is defined
