- name: Ensure group exists
  group:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ fabric_group }}"
    - "{{ elvmasterd_group }}"
  when: item is defined

- name: Add the service users
  user:
    name: "{{ item.user }}"
    shell: /bin/bash
    group: "{{ item.group }}"
    state: present
  loop:
    - { user: "{{ fabric_user }}", group: "{{ fabric_group }}" }
    - { user: "{{ elvmasterd_user }}", group: "{{ elvmasterd_group }}" }
  when: item.user is defined

